name: cluth_vscode_ver1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/icon/.

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: asset/font/MyFlutterApp.ttf
    - family: Pretendard-Bold
      fonts:
        - asset: asset/font/Pretendard-Bold.otf
    - family: Pretendard-Semi
      fonts:
        - asset: asset/font/Pretendard-SemiBold.otf
    - family: PretendardRegular
      fonts:
        - asset: asset/font/Pretendard-Regular.otf